### ISSUE TITLE
O que falta para rodar o miolo

### ISSUE THREAD

**Issue by lubrand** [hedra-editora/fichte_explosao#1]
1. Sumário
O comando pontinhos não está funcionando.
A contagem automática \setcounter{tocdepth}{0} \setcounter{secnumdepth}{0} também não funcionou muito bem, pelo make test vi que a nota de apresentação saiu com o título "Capítulo 1" grafado acima.

2. Publicidade
Como inserir o título de Hubert Fichte na lista de publicações da série Sexo, nas páginas finais?

**Comment by jorgesallum** [comment]
Pronto
